### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by eantones** [nuobit/odoo-addons#1]
# Todo
https://github.com/nuobit/odoo-addons/wiki/Migration-to-version-12.0

# Modules to migrate
- [ ] account_asset_active
- [ ] account_asset_comment
- [ ] account_asset_hook
- [ ] account_asset_invoice_line_link
- [ ] account_asset_non_deductible
- [ ] account_asset_non_depreciable
- [ ] account_asset_product_item
- [ ] account_bank_statement_balance_start_protection
- [ ] account_cash_statement_restrict
- [ ] account_financial_report_number
- [ ] account_invoice_batches
- [ ] account_invoice_hide_payment_button
- [ ] account_invoice_mass_email
- [ ] account_invoice_name_short
- [ ] account_invoice_report_service
- [ ] account_invoice_sent_flag
- [x] account_invoice_tax_analytic_account - By @eantones - #10
- [ ] account_template_menu
- [x] bank_multiple_acc_number - By @Vrajatechnologies - #8
- [ ] barcodes_gs1_label
- [ ] base_report_gs1_barcode
- [ ] base_report_pdf_css_reset
- [ ] connector_ambugest
- [ ] connector_ambumovil
- [ ] connector_common
- [ ] connector_oxigesti
- [ ] connector_oximovil
- [ ] connector_sage
- [ ] contract_comment
- [ ] contract_line_tax
- [ ] contract_sii
- [ ] custom_gj
- [ ] l10n_es_account_bank_statement_import_n43_overlap
- [ ] l10n_es_aeat_vat_special_prorrate
- [ ] l10n_es_facturae_auto_date
- [ ] l10n_es_facturae_sale_stock
- [ ] l10n_es_facturae_set_sent
- [ ] partner_default_journal - By @Vrajatechnologies - #9
- [x] partner_name_vat - By @Vrajatechnologies - #6
- [ ] partner_review
- [ ] payroll_sage
- [x] product_supplier_search - By @eantones - #3
- [ ] product_unique_barcode
- [x] product_unique_internal_reference - By @eantones - #4
- [ ] purchase_order_new_line_uom
- [ ] quality_partner
- [ ] report_qweb_pdf_chunks
- [ ] sale_line_partner_description
- [ ] sale_order_cancel_stock
- [ ] sale_order_invoice_date
- [ ] sale_order_invoiced_unlink
- [ ] sale_order_invoicing_exclude
- [ ] sale_order_service
- [ ] stock_barcodes_gs1_extended
- [ ] stock_inventory_additional_groups
- [ ] stock_location_code
- [ ] stock_location_localization_text
- [ ] stock_location_tag
- [ ] stock_orderpoint_manual_procurement_zero
- [ ] stock_orderpoint_sync_template
- [ ] stock_picking_employee
- [ ] stock_picking_import_serials
- [ ] stock_picking_line_description
- [ ] stock_picking_line_price
- [ ] stock_picking_partner
- [ ] stock_picking_partner_ref
- [ ] stock_picking_report_delivery_note
- [ ] stock_picking_report_location_order
- [ ] stock_picking_report_lot_size
- [ ] stock_picking_rpc_error
- [ ] stock_putaway_no_internal
- [ ] stock_putaway_no_internal_mrp
- [ ] web_login_default_logo
- [ ] website_decoupling
- [ ] website_decoupling_login_default_logo
