### ISSUE TITLE
Migration to version 14.0

### ISSUE THREAD

**Issue by eantones** [nuobit/odoo-addons#12]
# Todo
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

# Modules to migrate
- [x]  ~~account_asset_active - By @MiquelRForgeFlow - #56~~ - Already in core
- [x]  account_asset_comment - By @MiquelRForgeFlow - #57
- [x]  ~~account_asset_hook - By @MiquelRForgeFlow - #58~~ - Already in core
- [x]  ~~account_asset_invoice_account_date - By @MiquelRForgeFlow - #59~~ - Already in core
- [x]  account_asset_invoice_line_link - By @MiquelRForgeFlow - #60
- [x]  account_asset_non_deductible - By @ChrisOForgeFlow - #123
- [ ]  account_asset_non_depreciable
- [x] ~~account_asset_product_item - By @MiquelRForgeFlow - #61~~ - Already in new OCA asset module
- [x]  account_bank_statement_balance_start_protection - By @MiquelRForgeFlow - #13
- [x]  account_cash_statement_restrict - By @MiquelRForgeFlow - #14
- [x]  account_financial_report_number - By ChrisOForgeFlow - #131
- [x]  account_invoice_batches - By @ChrisOForgeFlow - #117
- [x]  account_invoice_hide_payment_button - By @MiquelRForgeFlow - #15
- [x]  account_invoice_line_page_size - By @KNVx - #98 
- [x]  account_invoice_mass_email - By @MiquelRForgeFlow - #16
- [x]  account_invoice_name_short - By @MiquelRForgeFlow - #17
- [x]  account_invoice_report_lot - By @KNVx - #111 
- [x]  account_invoice_report_service - By @MiquelRForgeFlow - #19
- [x] account_invoice_sent_flag - By @MiquelRForgeFlow - #20
- [x]  account_invoice_tax_analytic_account - By @eantones - #10 
- [x]  account_project_task_state - By @KNVx - #125 
- [x] ~~account_template_menu - By @MiquelRForgeFlow - #21~~ - Already in core
- [x]  bank_multiple_acc_number - By @MiquelRForgeFlow - #22
- [x]  barcodes_gs1_label - By @MiquelRForgeFlow - #25
- [x]  base_report_gs1_barcode - By @MiquelRForgeFlow - #23
- [x]  base_report_pdf_css_reset - By @MiquelRForgeFlow - #24
- [x]  connector_ambugest - By @KNVx - #95
- [x] ~~connector_ambumovil~~ - Replaced by stock_rest
- [x]  connector_common - By @KNVx - #145
- [x]  connector_oxigesti - By @KNVx - #94
- [x] ~~connector_oximovil~~ - Replaced by stock_rest
- [x]  connector_sage - By @KNVx - #93
- [x]  contract_comment - By @ChrisOForgeFlow - #130
- [x]  contract_line_tax - By @ChrisOForgeFlow - #129 
- [x]  contract_sii - by @ChrisOForgeFlow - #132 
- [x]  ~~custom_gj~~ - Moved to customer repo
- [x]  l10n_es_account_bank_statement_import_n43_overlap - By @MiquelRForgeFlow - #160
- [x]  l10n_es_aeat_mod303_special_prorate - By @eantones - #154
- [x]  l10n_es_aeat_sii_oca_special_prorate - By @eantones - #154
- [x]  l10n_es_aeat_vat_special_prorrate - By @eantones - #154
- [x]  l10n_es_facturae_auto_date - By @ChrisOForgeFlow - #135 
- [ ]  l10n_es_facturae_sale_stock
- [x]  l10n_es_facturae_service - By @ChrisOForgeFlow - #133
- [x]  l10n_es_facturae_set_sent - By @ChrisOForgeFlow - #134
- [x]  l10n_es_special_prorate - By @eantones - #154
- [x]  mrp_repair_employee - By @MiquelRForgeFlow - #26
- [x]  partner_default_journal - By @MiquelRForgeFlow - #27
- [x]  partner_name_vat - By @MiquelRForgeFlow - #28
- [x]  partner_review - By @MiquelRForgeFlow - #29
- [x]  payroll_sage - By @KNVx - #144 
- [x]  pos_product_pack - By @KNVx - #127 
- [x]  pos_product_service_time - By @KNVx - #128
- [x]  pos_restaurant_note_print - By @KNVx - #126
- [x]  product_bike_info - By @KNVx - #108 
- [x]  product_cost_hide - By @KNVx - #107 
- [x]  product_service_time - By @KNVx - #106 
- [x]  product_supplier_search - By @MiquelRForgeFlow - #30
- [x]  product_unique_barcode - By @MiquelRForgeFlow - #31
- [x]  product_unique_internal_reference - By @MiquelRForgeFlow - #32
- [x] project_legal_management - By @KNVx - #83
- [x]  project_task_alternate_name - By @KNVx - #115 
- [x]  project_task_bike_location - By @KNVx - #105 
- [x]  project_task_date_consistency - By @KNVx - #120 
- [x]  project_task_hide_tasks - By @KNVx - #104 
- [x]  project_task_metatype - By @KNVx - #103 
- [x]  project_timeline_calendar - By @KNVx - #116
- [x]  project_timeline_default_view - By @KNVx - #102 
- [x]  purchase_order_new_line_uom - By @MiquelRForgeFlow - #33
- [x]  quality_partner - By @MiquelRForgeFlow - #34
- [x]  report_qweb_pdf_chunks - By @MiquelRForgeFlow - #35
- [x] sale_line_partner_description - By @eantones - #85
- [x]  sale_order_bike_location - By @KNVx - #101 
- [x]  sale_order_cancel_stock - By @MiquelRForgeFlow - #37
- [x]  sale_order_date_show - By @KNVx - #100 
- [x]  sale_order_invoice_date - By @MiquelRForgeFlow - #38
- [x]  sale_order_invoiced_unlink - By @MiquelRForgeFlow - #39
- [x]  sale_order_invoicing_exclude - By @MiquelRForgeFlow - #40
- [x]  sale_order_line_page_size - By @KNVx - #99 
- [x]  sale_order_service - By @MiquelRForgeFlow - #18
- [x]  sale_order_task_autoassign - By @KNVx - #118 
- [x]  sale_order_task_autoassign_pack - By @KNVx - #119 
- [x]  sale_order_task_cancel - By @KNVx - #109 
- [x]  sale_report_product_type - By @KNVx - #110 
- [x]  stock_barcodes_gs1_extended - By @LoisRForgeFlow - #155
- [x]  stock_barcodes_sku - By @KNVx - #122 
- [x]  stock_inventory_additional_groups - By @MiquelRForgeFlow - #41
- [x] stock_location_code - By @MiquelRForgeFlow - #42
- [x]  stock_location_localization_text - By @MiquelRForgeFlow - #43
- [x]  stock_location_tag - By @MiquelRForgeFlow - #44
- [x] ~~stock_move_line_lot~~ - Included in core
- [x]  stock_move_line_picking - By @KNVx - #113 
- [x]  stock_move_line_sale_order - By @KNVx - #114 
- [x]  ~~stock_order_forecast~~  - Included in core
- [x]  stock_orderpoint_manual_procurement_zero - By @ChrisOForgeFlow - #124
- [x]  stock_orderpoint_sync_template - By @MiquelRForgeFlow - #45
- [x] stock_picking_employee - By @MiquelRForgeFlow - #46
- [x]  stock_picking_import_serials - By @eantones  - #86 
- [x]  stock_picking_line_description - By @MiquelRForgeFlow - #48
- [x]  stock_picking_line_price - By @MiquelRForgeFlow - #49
- [ ]  stock_picking_partner
- [x]  stock_picking_partner_ref - By @MiquelRForgeFlow - #50
- [x] stock_picking_partner_ref_search - By @KNVx - #121 
- [x]  stock_picking_report_delivery_note - By @MiquelRForgeFlow - #51
- [x]  stock_picking_report_location_order - By @MiquelRForgeFlow - #52
- [ ]  stock_picking_report_lot_size
- [x] ~~stock_picking_rpc_error~~ - Not needed anymore
- [x]  stock_putaway_no_internal - By @MiquelRForgeFlow - #53
- [x]  stock_putaway_no_internal_mrp - By @MiquelRForgeFlow - #54
- [x]  stock_rest - By @KNVx - #97
- [x] web_login_default_logo - By @eantones - #197 
- [x] ~~website_decoupling_login_default_logo~~ - Not needed anymore
- [x] ~~website_decoupling~~ - Not needed anymore

**Comment by MiquelRForgeFlow** [comment]
Hello @eantones, I have migrated a lot of modules of this list. Hope you check them soon.

Also, `stock_picking_partner`, `stock_picking_report_lot_size` and `stock_picking_rpc_error` modules are not needed to be migrated (because their feature is already included in core). And I think  `account_invoice_tax_analytic_account` cannot be migrated as it is, the code in v14 has changed too much and that feature cannot be implemented that way. And `account_asset_non_depreciable` is not needed anymore.

**Comment by KNVx** [comment]
Hi @eantones , I'm migrating project_legal_management module.
https://github.com/nuobit/odoo-addons/pull/83

**Comment by ChrisOForgeFlow** [comment]
@eantones I review module account_invoice_tax_analytic_account and see that this functionality is implemented on core

https://github.com/odoo/odoo/blob/96e4f84d94480362ebbf3841951852f09c7080fc/addons/account/models/account_move.py#L549

You can configure tax if should be grouped by analytic account and analytic tags

![image](https://user-images.githubusercontent.com/94866688/147761164-965de18d-b371-406b-821c-cc562fd6361f.png)

I recommend depreciate module
