### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by eantones** [nuobit/odoo-addons#344]
# Todo
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate
- [x] ~~account_asset_comment~~ - Deprecated
- [ ] account_asset_invoice_line_link - By @deeniiz - #517 
- [ ] account_asset_management_extension - By @bjkumal - #564 
- [ ] account_asset_non_deductible
- [x] account_asset_report_category - By @deeniiz - #534 
- [x] account_asset_tax_consistency - By @bjkumal - #569 
- [ ] account_asset_transfer_extension
- [ ] account_bank_statement_balance_start_protection - By @deeniiz
- [ ] account_cash_statement_restrict
- [ ] account_facturae_attach_existing_attachment
- [x] account_financial_report_multi_company - By @deeniiz - #535 
- [ ] account_financial_report_number - By @deeniiz - #553 
- [ ] account_invoice_attachment_required - By @deeniiz -
- [ ] account_invoice_batches
- [ ] account_invoice_batches_accrual_entry
- [x] account_invoice_hide_payment_button - By @bjkumal - #510 
- [x] account_invoice_line_page_size - By @bjkumal - #519 
- [ ] account_invoice_mass_email - By @deeniiz - #555
- [ ] account_invoice_name_short - By @deeniiz -
- [ ] account_invoice_report_lot - By @deeniiz
- [ ] account_invoice_report_service
- [ ] account_invoice_report_service_facturae
- [ ] account_invoice_same_accounting_date - By @deeniiz -
- [ ] account_invoice_same_accounting_date_prorate
- [ ] account_invoice_sent_flag - By @deeniiz - #493 
- [ ] account_invoices_batches_mail_attach_existing_attachment
- [x] ~~account_journal_entry_filter_number - By @bjkumal - #518~~ - Deprecated
- [ ] account_mail_attach_existing_attachment
- [ ] account_move_accrual_entry - By @deeniiz
- [ ] account_move_asset_review
- [ ] account_move_service
- [ ] account_move_service_report_xlsx
- [ ] account_move_show_date_out_invoices
- [ ] account_payment_partner_sorted - By @bjkumal - #520
- [ ] account_project_task_state
- [ ] account_template_view - By @deeniiz - #554 
- [ ] bank_multiple_acc_number
- [x] barcodes_gs1_label - By @deeniiz - #541 
- [x] barcodes_gs1_label_expiry - By @deeniiz - #565 
- [x] barcode_label_template - By @deeniiz - #557 
- [x] base_report_gs1_barcode - By @deeniiz - #538 
- [x] base_report_pdf_css_reset - By @deeniiz - #539 
- [x] base_user_update_partner - By @deeniiz - #501 
- [ ] connector_ambugest
- [ ] connector_cbl - By @KNVx - #355
- [x] ~~connector_common~~ - Deprecated
- [x] connector_ertransit - By @KNVx - #356
- [ ] connector_extension
- [ ] connector_extension_mssql
- [ ] connector_extension_mysql
- [ ] connector_extension_sql
- [x] connector_lengow - By @KNVx - #345
- [x] ~~connector_lengow_debug~~ - Deprecated
- [ ] connector_oxigesti
- [ ] connector_sage
- [x] connector_sapb1 - By @KNVx - #347
- [ ] connector_veloconnect
- [ ] connector_veloconnect_fuchs_movesa
- [x] contract_comment - By @deeniiz -
- [ ] contract_line_tax
- [ ] contract_mandate_default - By @bjkumal - #521 
- [ ] contract_payment_mode_partner
- [ ] contract_sii
- [ ] crm_lost_stage - By @deeniiz -
- [ ] delivery_mrw_no_info
- [ ] display_name_mixin
- [ ] l10n_es_account_asset_tax_consistency
- [ ] l10n_es_account_asset_tax_consistency_prorate
- [ ] l10n_es_account_capital_asset
- [ ] l10n_es_account_capital_asset_tax_map
- [ ] l10n_es_account_capital_asset_tax_map_prorate
- [x] l10n_es_account_menu - By @bjkumal - #527 
- [ ] l10n_es_account_statement_import_n43_company
- [ ] l10n_es_account_statement_import_n43_overlap
- [ ] l10n_es_aeat_mod303_special_prorate
- [x] l10n_es_aeat_extension - By @bjkumal - #528 
- [ ] l10n_es_aeat_mod303_special_prorate_regularization
- [ ] l10n_es_aeat_mod303_special_prorate_regularization_capital_asset
- [ ] l10n_es_aeat_mod303_special_prorate_regularization_capital_asset_auc
- [ ] l10n_es_aeat_mod303_special_prorate_regularization_capital_asset_legacy
- [ ] l10n_es_aeat_mod303_special_prorate_regularization_prorate
- [ ] l10n_es_aeat_prorate_asset
- [ ] l10n_es_aeat_sii_oca_extension
- [ ] l10n_es_aeat_sii_oca_mock
- [ ] l10n_es_aeat_sii_oca_special_prorate
- [ ] l10n_es_aeat_sii_special_prorate_regularization_capital_asset
- [ ] l10n_es_aeat_sii_special_prorate_regularization_capital_asset_mock
- [ ] l10n_es_aeat_vat_special_prorrate
- [ ] l10n_es_aeat_vat_special_prorrate_purchase
- [ ] l10n_es_asset_extension
- [ ] l10n_es_banking_sepa_direct_debit_order_sabadell
- [ ] l10n_es_dua_special_prorrate
- [x] l10n_es_extension - @bjkumal - #529 
- [ ] l10n_es_facturae_auto_date
- [ ] l10n_es_facturae_auto_date_contract
- [ ] l10n_es_facturae_cege
- [ ] l10n_es_facturae_default_bank_account
- [ ] l10n_es_facturae_service
- [ ] l10n_es_facturae_set_sent
- [ ] l10n_es_facturae_tax_rounding
- [ ] l10n_es_special_prorate
- [ ] maintenance_request_date_editable
- [x] partner_default_company - By @bjkumal - #495 
- [ ] partner_default_journal - By @deeniiz - #483
- [ ] partner_document
- [ ] partner_email_mobile_required
- [ ] partner_firstname_swap_position - By @deeniiz -
- [x] partner_lang_required - By @deeniiz -
- [ ] partner_name_reference - By @deeniiz -
- [x] partner_name_vat - By @deeniiz -
- [x] partner_review - By @bjkumal - #496 
- [ ] payroll_sage - By @deeniiz - #504 
- [ ] pos_product_pack
- [ ] pos_product_service_time
- [ ] pos_restaurant_note_print
- [ ] pricelist_massive_update_contract
- [ ] product_bike_info
- [ ] product_cost_hide - By @bjkumal - #516 
- [x] product_expiry_removal_required - By @bjkumal - #526 
- [ ] product_image_removal_required
- [ ] product_multi_unique_barcode
- [ ] product_service_time
- [ ] product_supplier_ref - By @bjkumal - #507
- [ ] product_supplier_search - By @deeniiz - #513 
- [ ] product_supplierinfo_unique - By @bjkumal - #505 
- [ ] product_unique_barcode - By @bjkumal - #515 
- [x] product_unique_internal_reference - By @bjkumal - #503 
- [ ] project_category_parent_group
- [ ] project_legal_management - By @deeniiz - #502 
- [ ] project_task_alternate_name
- [ ] project_task_bike_location
- [ ] project_task_date_consistency
- [ ] project_task_hide_tasks
- [ ] project_task_metatype
- [ ] project_timeline_calendar
- [ ] project_timeline_default_view
- [ ] purchase_order_new_line_uom
- [ ] purchase_stock_order_description
- [ ] purchase_stock_supplier_product_code
- [x] quality_partner - By @bjkumal - #547 
- [x] repair_employee - By @bjkumal - #509 
- [ ] repair_order_default_location - By @deeniiz - #532 
- [x] report_json - By @KNVx - #357
- [ ] report_qweb_pdf_chunks
- [ ] res_lang_shortname - By @deeniiz -
- [ ] sale_line_partner_description
- [ ] sale_order_bike_location
- [ ] sale_order_cancel_stock
- [ ] sale_order_date_show
- [x] ~~sale_order_email_import~~ - Deprecated
- [ ] sale_order_invoice_date
- [ ] sale_order_invoiced_unlink - By @deeniiz - #475
- [ ] sale_order_invoicing_exclude
- [ ] sale_order_line_page_size
- [ ] sale_order_margin
- [ ] sale_order_service
- [ ] sale_order_task_autoassign
- [ ] sale_order_task_autoassign_pack
- [ ] sale_order_task_cancel
- [ ] sale_report_product_bike_info
- [ ] sale_report_product_type
- [ ] sale_specific_order_date
- [ ] stock_barcodes_gs1_extended
- [ ] stock_barcodes_option_new_scan
- [ ] stock_barcodes_qty_virtual_location
- [ ] stock_barcodes_serial_autoconfirm
- [ ] stock_barcodes_serial_source_relocation
- [ ] stock_barcodes_sku
- [ ] stock_barcodes_unique_field
- [ ] stock_inventory_additional_groups
- [x] stock_location_code - By @bjkumal - #514 
- [ ] stock_location_flowable
- [ ] stock_location_localization_text
- [x] stock_location_tag - By @bjkumal - #512 
- [ ] stock_move_line_picking - By @bjkumal - #497 
- [ ] stock_move_line_sale_order
- [ ] stock_move_no_merge
- [ ] stock_orderpoint_manual_procurement_zero
- [ ] stock_orderpoint_qty_restrict
- [ ] stock_orderpoint_sync_template
- [ ] stock_picking_date_filter - By @bjkumal - #498
- [x] stock_picking_default_product_search - By @bjkumal - #511 
- [ ] stock_picking_employee - By @deeniiz -
- [x] stock_picking_import_serials - By @deeniiz - #537 
- [ ] stock_picking_line_description
- [ ] stock_picking_line_location_order
- [ ] stock_picking_line_price
- [x] stock_picking_partner_ref - By @deeniiz - #243 
- [ ] stock_picking_partner_ref_search
- [ ] stock_picking_report_delivery_note
- [ ] stock_picking_report_delivery_note_kit
- [ ] stock_picking_report_location_order
- [ ] stock_putaway_no_internal
- [ ] stock_putaway_no_internal_mrp
- [ ] stock_reordering_inmediate_transfer
- [ ] stock_rest
- [ ] stock_restrict_lot_name
- [ ] stock_tracking_integrity
- [ ] stock_unique_serial
- [ ] tools_mimetypes_extension
- [ ] translation_auto - By @KNVx - #361
- [ ] web_line_page_size
- [x] web_login_default_logo - By @deeniiz - #540 
- [x] web_notebook_wrap - By @KNVx - #362
- [x] website_erp_login - By @bjkumal - #533 
- [ ] website_erp_login_default_logo - By @bjkumal

**Comment by eantones** [comment]
@KNVx

**Comment by eantones** [comment]
@bjkumal @deeniiz Just FYI, you can check the overall migration status from here
